name: Run dbt models

on:
  push:
    branches:
      - main

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt

    - name: Configure GCP credentials
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" > creds.json
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    - name: Run dbt models
      run: |
        dbt run 
